### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
We are working with dr.lt.data and comfyanon to build a global registry for custom nodes (similar to PyPI). Eventually, the registry will be used as a backend for the UI-manager. All nodes go through a verification process before being published to users.

The main benefits are that authors can
- publish nodes by version and users can safely update nodes knowing ahead of time if their workflows will break or not
- automate testing against new commits in the comfy repo and existing workflows through our CI/CD dashboard

Action Required:

- [ ] Go to the [registry](https://registry.comfy.org). Login and create a publisher id. Add the publisher id into the pyproject.toml file.
- [ ] Write a short description.
- [ ] Merge the separate Github Actions PR and run the workflow.

If you want to publish the node manually, [install the cli](https://docs.comfy.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`

Check out our [docs](https://docs.comfy.org/registry/overview#introduction) if you want to know more about the registry. Otherwise, feel free to message me on discord at haohao_81202 or join our [server](https://discord.com/invite/comfyorg) if you have any questions!

### CODE REVIEW

**Comment by haohaocreates** [comment]
hey @cdb-boop, wanted to send a small nudge and ask if you had any questions!

**Comment by haohaocreates** [comment]
@cdb-boop, wondering if there's any way we can support you on this PR!

**Comment by cdb-boop** [comment]
I followed the instructions, but the node won't publish. The command line tool fails and manually running the Github action through the browser fails.

```
Validating node configuration...
Please enter your API Key (can be created on https://registry.comfy.org):
Publishing node version...
{'Failed to publish node version: 400
{"message":"Failed to validate token"}\n'}
```

**Comment by haohaocreates** [comment]
hey @cdb-boop , I can't seem to find your publisher ID account on our backend? in your toml file it says your publisher ID is "bringing-old-photos-back-to-life" 

can you link me your profile or registry account and I can try to debug?

**Comment by cdb-boop** [comment]
My publisher name is `cdb-boop` and the publisher id is `bringing-old-photos-back-to-life`. I did get a key.

**Comment by haohaocreates** [comment]
> My publisher name is `cdb-boop` and the publisher id is `bringing-old-photos-back-to-life`. I did get a key.

Hey @cdp-boop


Okay first thing you might want to do is change your toml file so that cdb-boop is your pid, I'll look into this tn though

**Comment by haohaocreates** [comment]
> cdb-boop

hey @cdb-boop , in the backend it seems that your publisher ID is "cdb-boop". We don't have any publisher under your other account. The publisher id is everything after the "@" sign on your profile page. 

could you change your publisher ID to "cdb-boop" and try again?

**Comment by cdb-boop** [comment]
There is no "@" sign. And, how can I change my publisher id from "cdb-boop" to "cdb-boop"?

Screenshot 2024-07-28 205143

**Comment by cdb-boop** [comment]
I tried that earlier, but it seems that VSCode command line wasn't registering my paste keyboard shortcut... However, I got it working now. Thanks!

**Pull request closed without merging**
